TrainingArguments:
  num_train_epochs: 25
  warmup_steps: 500
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  weight_decay: 0.01
  logging_steps: 10
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 1000
  gradient_accumulation_steps: 16