artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1nCJWFEB_kWSpnTAWwIOcN9p5EaoUpBcy/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip 
  unzip_dir:  artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ['train', 'test', '._dataset_dict.json', '._test', '._train', 'dataset_dict.json']

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data
  tokenizer_path: artifacts/data_transformation/tokenizer/

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/data
  model_ckpt_path: artifacts/model_trainer/model

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/data
  model_path: artifacts/model_trainer/distilbert-qa-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
